//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the XsdCodeGenerator, Version=2.23.608.0, Culture=neutral, PublicKeyToken=930d621ce8556c2f tool.
//     Tool Version:    2.23.608.0
//     Runtime Version: 4.0.30319.42000
//     Generated on:    2025-04-07 17:32:15
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. For more information see http://BlueToque.ca
// </autogenerated>
//------------------------------------------------------------------------------

//	http://BlueToque.ca
// Workaround for bug http://lab.msdn.microsoft.com/productfeedback/viewfeedback.aspx?feedbackid=d457a36e-0ce8-4368-9a27-92762860d8e1
#pragma warning disable 1591
namespace BlueToque.Utility.Windows
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BlueToque.ca/TrueNorth.Meridian/FormSettingsType")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://BlueToque.ca/TrueNorth.Meridian/FormSettingsType", IsNullable=true)]
    public partial class FormSettingsType : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        [field: System.NonSerialized()]
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private int stateField;
        
        /// <remarks/>
        public int State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <summary />
        private int locationXField;
        
        /// <remarks/>
        public int LocationX {
            get {
                return this.locationXField;
            }
            set {
                this.locationXField = value;
                this.RaisePropertyChanged("LocationX");
            }
        }
        
        /// <summary />
        private int locationYField;
        
        /// <remarks/>
        public int LocationY {
            get {
                return this.locationYField;
            }
            set {
                this.locationYField = value;
                this.RaisePropertyChanged("LocationY");
            }
        }
        
        /// <summary />
        private int sizeWidthField;
        
        /// <remarks/>
        public int SizeWidth {
            get {
                return this.sizeWidthField;
            }
            set {
                this.sizeWidthField = value;
                this.RaisePropertyChanged("SizeWidth");
            }
        }
        
        /// <summary />
        private int sizeHeightField;
        
        /// <remarks/>
        public int SizeHeight {
            get {
                return this.sizeHeightField;
            }
            set {
                this.sizeHeightField = value;
                this.RaisePropertyChanged("SizeHeight");
            }
        }
    }
}
#pragma warning restore 1591